/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-23 09:16:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/includes/footer.jsp", Long.valueOf(1577091987200L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1576631602713L));
    _jspx_dependants.put("jar:file:/C:/Spring_WS_2019/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ex00/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1577091879957L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("            $( function() {\r\n");
      out.write("              $( \"#accordion\" ).accordion();\r\n");
      out.write("            } );\r\n");
      out.write("            </script>\r\n");
      out.write("          </head>\r\n");
      out.write("          <body>\r\n");
      out.write("    <title>ë§ì»¨ì½ë¦¬ì ííì´ì§</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        *{padding:0;margin:0;}\r\n");
      out.write("        ul, li{list-style: none;}\r\n");
      out.write("        .container{padding:0;overflow: hidden;}\r\n");
      out.write("        .navbar {margin-bottom: 0;background-color: white;z-index: 9999;border: 0;font: 15px bold black;line-height: 1.42857143 !important;letter-spacing: 4px;border-radius: 0;}\r\n");
      out.write("        .navbar li a, .navbar .navbar-brand {color: black;}\r\n");
      out.write("        .nav li{padding-left:50px;}\r\n");
      out.write("        .navbar-toggler {background-color:darkgray;color: #fff !important;}\r\n");
      out.write("        .carousel-inner img {width: 100%;height: 100%;}\r\n");
      out.write("        .col-md-6, .col-sm-4{width:100%;box-sizing: border-box;padding:0;overflow: hidden;float:left;position:relative;}\r\n");
      out.write("        /* .col-md-6{max-height:771px;} */\r\n");
      out.write("        /* .col-sm-3{height:524px;} */\r\n");
      out.write("        /* .col-sm-4{height:500px;} */\r\n");
      out.write("        .caption{width:100%;position: absolute;bottom:20px;text-align:center;color:white;font-size:1vw;}\r\n");
      out.write("        /* .row1, .row2{padding-top:10px;}\r\n");
      out.write("        .row1 img{transform:scale(1);transition: 0.5s;height:100%}\r\n");
      out.write("        .row1 img:hover{transform: scale(1.05);}\r\n");
      out.write("        .row2 img{transform:scale(1);transition: 0.8s;height:100%}\r\n");
      out.write("        .row2 img:hover{transform: scale(1.1);}*/\r\n");
      out.write("\r\n");
      out.write("        .s-img-2{display: none;}\r\n");
      out.write("\r\n");
      out.write("        #caption2{position:absolute;top:32%;}\r\n");
      out.write("        #caption3{position:absolute;top:70%;right:5%;text-align: right;}\r\n");
      out.write("        #caption4{position:absolute;top:30%;right:-62%;}\r\n");
      out.write("        #caption5{position:absolute;top:25%;right:5%;text-align: right;}\r\n");
      out.write("\r\n");
      out.write("        #box1,#box2{padding-top:10px;box-sizing: border-box;}\r\n");
      out.write("        #box-left{box-sizing: border-box !important;height: 700px;}\r\n");
      out.write("        #box-right1, #box-right2{box-sizing: border-box !important;height:500px;overflow: hidden;}\r\n");
      out.write("        #box-bottom{box-sizing: border-box !important;height:200px;}\r\n");
      out.write("        #box1 img{transform:scale(1);transition:0.5s;height:100%;}\r\n");
      out.write("        #box1 img:hover{transform:scale(1.05);}\r\n");
      out.write("        #box2 .image{transform:scale(1);transition:0.8s;height:100%;}\r\n");
      out.write("        #box2 .image:hover{transform:scale(1.1);}\r\n");
      out.write("        \r\n");
      out.write("        .modal-body{float:left;}\r\n");
      out.write("        .modal-content{width:900px;height:700px;box-sizing: border-box;}\r\n");
      out.write("        .modal-header img{width:100%;}\r\n");
      out.write("        #myModal2 .modal-body div{height:30px;}\r\n");
      out.write("        #board{padding:50px 0;}\r\n");
      out.write("        #bottom-menu{padding-left:50px;margin:30px;}\r\n");
      out.write("        #bottom-menu a, .accordion a{text-decoration:none;font-size:14px;color:darkgray;margin:5px 0;transition: 0.5s;}\r\n");
      out.write("        #bottom-menu a:hover{color:#C55F07;}\r\n");
      out.write("        .accordion a:hover{color:#C55F07;}\r\n");
      out.write("        .accordion {display: none;background-color: white;color: #444;cursor: pointer;padding: 18px;width: 100%;border: none;text-align: left;outline: none;font-size: 15px;transition: 0.4s;}\r\n");
      out.write("        .panel {padding: 0 18px;background-color: white;max-height: 0;overflow: hidden;transition: max-height 0.2s ease-out;}\r\n");
      out.write("        .panel a{padding-left:40px;text-decoration: none;color:darkgray;font-size:14px;transition: 0.5s;}\r\n");
      out.write("        .panel a:hover{color:#C55F07;}\r\n");
      out.write("        footer .container{background:black; color:darkgray;margin:auto;text-align: center;font-size:14px;padding:10px 0;}\r\n");
      out.write("        .container span{padding-left:20px;padding-right:30px;outline: none;}\r\n");
      out.write("        footer a{text-decoration: none;color:darkgray;}\r\n");
      out.write("        footer a:hover{text-decoration: none;color:darkgray;}\r\n");
      out.write("        footer a:active{text-decoration: none;color:darkgray;}\r\n");
      out.write("\r\n");
      out.write("        @media screen and (max-width:768px){\r\n");
      out.write("            #box-left, #box-right1, #box-right2, #box-bottom{width:100px;height:400px;}\r\n");
      out.write("            .s-img-1{display: none;}\r\n");
      out.write("            .s-img-2{display: block;}\r\n");
      out.write("            #caption2{position:absolute;top:75%;}\r\n");
      out.write("            #caption4{position:absolute;top:86%;right:15%;}\r\n");
      out.write("            #caption5{position:absolute;top:12%;}\r\n");
      out.write("            .accordion{display: block;padding-left:30px;}\r\n");
      out.write("            #bottom-menu{display:none;}\r\n");
      out.write("            .caption{bottom:30%;}\r\n");
      out.write("            #bottom-menu h5{padding-top:30px;}\r\n");
      out.write("            .btn-block{text-align: left;color:black;}\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // iframe resize\r\n");
      out.write("        function autoResize(i)\r\n");
      out.write("        {\r\n");
      out.write("            (i).height=0;\r\n");
      out.write("            var iframeHeight=\r\n");
      out.write("            (i).contentWindow.document.body.scrollHeight;\r\n");
      out.write("            (i).height=iframeHeight+20;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $ (\"html,body\").animate({scrollTop : 0}, \"slow\");\r\n");
      out.write("\r\n");
      out.write("    //  $( \".delegate_update_success\" ).click(function() {\r\n");
      out.write("    //      location.reload(true);\r\n");
      out.write("    //      document.body.scrollTop=0\r\n");
      out.write("    // });\r\n");
      out.write("        // Add smooth scrolling to all links\r\n");
      out.write("        $(\"a\").on('click', function(event) {\r\n");
      out.write("\r\n");
      out.write("          // Make sure this.hash has a value before overriding default behavior\r\n");
      out.write("          if (this.hash !== \"\") {\r\n");
      out.write("            // Prevent default anchor click behavior\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            // Store hash\r\n");
      out.write("            var hash = this.hash;\r\n");
      out.write("\r\n");
      out.write("            // Using jQuery's animate() method to add smooth page scroll\r\n");
      out.write("            // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area\r\n");
      out.write("            $('html, body').animate({\r\n");
      out.write("              scrollTop: $(hash).offset().top\r\n");
      out.write("            }, 800, function(){\r\n");
      out.write("\r\n");
      out.write("              // Add hash (#) to URL when done scrolling (default click behavior)\r\n");
      out.write("              window.location.hash = hash;\r\n");
      out.write("            });\r\n");
      out.write("          } // End if\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("      </script>\r\n");
      out.write("</head>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"60\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <nav class=\"navbar navbar-expand-lg fixed-top sticky-top\">\n");
      out.write("            <!-- Brand -->\n");
      out.write("            <a class=\"navbar-brand\" href=\"#myPage\"><img src=\"resources/img/logo_cap.png\" alt=\"logo\"></a>\n");
      out.write("            \n");
      out.write("            <!-- Toggler/collapsibe Button -->\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            \n");
      out.write("            <!-- Navbar links -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\n");
      out.write("                <ul class=\"nav navbar-nav ml-auto\">\n");
      out.write("                <li class=\"nav-item\"  data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#box1\">ì ì²´ëª¨ë¸</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\"  data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#box2\">ì ìì¥</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\"  data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#board\">ê°ì¸ì ë³´ì·¨ê¸ë°©ì¹¨</a>\n");
      out.write("                </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("    </div>\n");
      out.write("    <!---------------------- Carousel --------------------------->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div id=\"demo\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("\n");
      out.write("                <!-- Indicators -->\n");
      out.write("                <ul class=\"carousel-indicators\">\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"1\"></li>\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"2\"></li>\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"3\"></li>\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"4\"></li>\n");
      out.write("                </ul>\n");
      out.write("            \n");
      out.write("                <!-- The slideshow -->\n");
      out.write("                <div class=\"carousel-inner\">\n");
      out.write("                    <div class=\"carousel-item active\">\n");
      out.write("                        <a href=\"https://www.lincoln-korea.com/vehicles/aviator/\" target=\"_blank\"><img class=\"s-img-1\" src=\"resources/img/img01.png\" alt=\"aviator\"></a>\n");
      out.write("                        <a href=\"https://www.lincoln-korea.com/vehicles/aviator/\" target=\"_blank\"><img class=\"s-img-2\" src=\"resources/img/mimg01.png\" alt=\"aviator\"></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/nb_img02.png\" alt=\"nautilus\" usemap=\"#nautilus\">\n");
      out.write("                        <!-- <map name=\"nautilus\">\n");
      out.write("                            <area target=\"_blank\" alt=\"ë§ì»¨ NAUTILUS\" title=\"ë§ì»¨ NAUTILUS\" href=\"https://www.lincoln-korea.com/vehicles/nautilus/\" coords=\"619,251,821,295\" shape=\"rect\">\n");
      out.write("                        </map> -->\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/nb_mimg02.png\" alt=\"nautilus\">\n");
      out.write("                        <div class=\"carousel-caption\" id=\"caption2\">\n");
      out.write("                            <a href=\"https://www.lincoln-korea.com/vehicles/nautilus/\" target=\"_blank\" class=\"btn btn-outline-light\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/nb_img03.png\" alt=\"mkc\" usemap=\"#mkc\">\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/nb_mimg03.png\" alt=\"mkc\">\n");
      out.write("                        <div class=\"carousel-caption\" id=\"caption3\">\n");
      out.write("                            <h1>NEW LINCOLN MKC</h1>\n");
      out.write("                            <h6>URBAN SUV, ìì ì ì¬ë¡ì¡ë¤!</h6>\n");
      out.write("                            <a href=\"https://www.lincoln-korea.com/vehicles/mkc.html/\" target=\"_blank\" class=\"btn btn-outline-light\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/nb_img04.png\" alt=\"continental\">\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/nb_mimg04.png\" alt=\"continental\">\n");
      out.write("                        <div class=\"carousel-caption\" id=\"caption4\">\n");
      out.write("                            <a href=\"https://www.lincoln-korea.com/vehicles/continental/\" target=\"_blank\" class=\"btn btn-outline-light\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/nb_img05.png\" alt=\"mkz\">\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/nb_mimg05.png\" alt=\"mkz\">\n");
      out.write("                        <div class=\"carousel-caption\" id=\"caption5\" style=\"color:black;\">\n");
      out.write("                            <h1>LINCOLN MKZ</h1>\n");
      out.write("                            <h6>ìëì ì¸ ì²«ì¸ì, ë¹ì ì²ë¼</h6>\n");
      out.write("                            <a href=\"https://www.lincoln-korea.com/vehicles/mkz/\" target=\"_blank\" class=\"btn btn-outline-dark\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("                <!-- Left and right controls -->\n");
      out.write("                <a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\n");
      out.write("                <span class=\"carousel-control-prev-icon\"></span>\n");
      out.write("                </a>\n");
      out.write("                <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\n");
      out.write("                <span class=\"carousel-control-next-icon\"></span>\n");
      out.write("                </a>\n");
      out.write("            \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!------- Carousel END ---------->\n");
      out.write("\n");
      out.write("    <!-- ë°ì¤ -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\" id=\"box1\">\n");
      out.write("            <div class=\"col-md-6 col-12\" id=\"box-left\">\n");
      out.write("                <img class=\"s-img-1\" src=\"resources/img/img06.png\" alt=\"ì ì²´ëª¨ë¸ì´ë¯¸ì§\" width=\"100%\">\n");
      out.write("                <img class=\"s-img-2\" src=\"resources/img/mimg06.png\" alt=\"ì ì²´ëª¨ë¸ì´ë¯¸ì§\" width=\"100%\">\n");
      out.write("                <div class=\"caption\">\n");
      out.write("                    <h4>See All Lincoln</h4>\n");
      out.write("                    <p>ë¹ì ë§ì ìí ë§ì»¨ì ëª¨ë¸ì íì¸í´ë³´ì¸ì</p>\n");
      out.write("                    <a href=\"#\" class=\"btn btn-outline-light text-white\">ì ì²´ ëª¨ë¸ ë³´ê¸° ></a> \n");
      out.write("                </div> \n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-12\">\n");
      out.write("                <div class=\"row\" id=\"box-right\">\n");
      out.write("                    <div class=\"col-md-6 col-12\" id=\"box-right1\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/img07.png\" alt=\"ì¸íë¦¬ì í¸\" width=\"100%\">\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/mimg07.png\" alt=\"ì¸íë¦¬ì í¸\" width=\"100%\">\n");
      out.write("                        <div class=\"caption\">\n");
      out.write("                            <h4>Technology</h4>\n");
      out.write("                            <p>ë§ì»¨ ì¸íë¦¬ì í¸ AWD</p>\n");
      out.write("                            <a href=\"#\" class=\"btn btn-outline-light text-white\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 col-12\" id=\"box-right2\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/img08.png\" alt=\"íë¦¬ë¯¸ììë¹ì¤\" width=\"100%\">\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/mimg08.png\" alt=\"íë¦¬ë¯¸ììë¹ì¤\" width=\"100%\">\n");
      out.write("                        <div class=\"caption\">\n");
      out.write("                            <h4>Pick up & Delivery</h4>\n");
      out.write("                            <p>ì§ì  ì°¾ìê°ë íë¦¬ë¯¸ììë¹ì¤</p>\n");
      out.write("                            <a href=\"#\" class=\"btn btn-outline-light text-white\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12 col-12\" id=\"box-bottom\">\n");
      out.write("                        <img class=\"s-img-1\" src=\"resources/img/img09.png\" alt=\"ì¸ì¼ì¦íë¡ëª¨ì\" width=\"100%\">\n");
      out.write("                        <img class=\"s-img-2\" src=\"resources/img/mimg09.png\" alt=\"ì¸ì¼ì¦íë¡ëª¨ì\" width=\"100%\">\n");
      out.write("                        <div class=\"caption\">\n");
      out.write("                            <h4>Sales Promotion</h4>\n");
      out.write("                            <p>ì§í ì¤ì¸ ì¸ì¼ì¦ íë¡ëª¨ì</p>\n");
      out.write("                            <a href=\"#\" class=\"btn btn-outline-light text-white\">ìì¸í ë³´ê¸° ></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>  \n");
      out.write("    <!--ë°ì¤ë -->\n");
      out.write("\n");
      out.write("    <!----------------------------- Third Row ----------------------------->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\" id=\"box2\">\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("                <img src=\"resources/img/img10.png\" alt=\"ìë¹ì¤ì¼í°\" width=\"100%\" class=\"image\">\n");
      out.write("                <div class=\"caption\">\n");
      out.write("                    <h4>ì ìì¥ ë° ìë¹ì¤ì¼í° ì°¾ê¸°</h4>\n");
      out.write("                    <a href=\"#\" class=\"btn btn-outline-light text-white\" data-toggle=\"modal\" data-target=\"#myModal\">ë°ë¡ ê°ê¸° ></a>\n");
      out.write("                    <!-------------- The Modal --------------->\n");
      out.write("                    <div class=\"modal\" id=\"myModal\">\n");
      out.write("                        <div class=\"modal-dialog\">\n");
      out.write("                            <div class=\"modal-content\">\n");
      out.write("                                <!---- Modal Header ---->\n");
      out.write("                                <div class=\"modal-header\">\n");
      out.write("                                <h4 class=\"modal-title\" style=\"color:black;\">ì ìì¥ ìì¹</h4>\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                                </div>\n");
      out.write("                                <!---- Modal body ---->\n");
      out.write("                                <div class=\"modal-body\">\n");
      out.write("                                    <div id=\"kakaomap\" style=\"width: 100%;height: 500px;\"></div>\n");
      out.write("                                    <script type=\"text/javascript\" src=\"http://dapi.kakao.com/v2/maps/sdk.js?appkey=00291b6743bb5f372557da7b5c5afa29\"></script>\n");
      out.write("                                        <script> \n");
      out.write("                                            $(\"#myModal\").on(\"shown.bs.modal\", function (){\n");
      out.write("                                                var mapContainer = document.getElementById('kakaomap'), // ì§ëë¥¼ íìí  div \n");
      out.write("                                                mapOption = { \n");
      out.write("                                                            center: new daum.maps.LatLng(37.525015, 126.907642), // ì§ëì ì¤ì¬ì¢í\n");
      out.write("                                                            level: 3 // ì§ëì íë ë ë²¨\n");
      out.write("                                                        };\n");
      out.write("                                                var map = new daum.maps.Map(mapContainer, mapOption); // ì§ëë¥¼ ìì±í©ëë¤\n");
      out.write("                                                // ë§ì»¤ê° íìë  ìì¹ìëë¤ \n");
      out.write("                                                var markerPosition  = new daum.maps.LatLng(37.525015, 126.907642);\n");
      out.write("                                                // ë§ì»¤ë¥¼ ìì±í©ëë¤\n");
      out.write("                                                var marker = new daum.maps.Marker({\n");
      out.write("                                                    position: markerPosition\n");
      out.write("                                                    });\n");
      out.write("                                                // ë§ì»¤ê° ì§ë ìì íìëëë¡ ì¤ì í©ëë¤\n");
      out.write("                                                marker.setMap(map);\n");
      out.write("                                            });\n");
      out.write("                                        </script>\n");
      out.write("                                        <!-- ì¹´ì¹´ì¤ë§µ.ë.-->\n");
      out.write("                                </div>\n");
      out.write("                                <!---- Modal footer ---->\n");
      out.write("                                <div class=\"modal-footer\">\n");
      out.write("                                <button type=\"button\" class=\"btn btn-dark\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!--------- The Modal END --------->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("                <img src=\"resources/img/img11.png\" alt=\"ë¸ë¡ì\" width=\"100%\" class=\"image\">\n");
      out.write("                <div class=\"caption\">\n");
      out.write("                    <h4>ë¸ë¡ì ë³´ê¸°</h4>\n");
      out.write("                    <a href=\"#\" class=\"btn btn-outline-light text-white\" data-toggle=\"modal\" data-target=\"#myModal2\">ë°ë¡ ê°ê¸° ></a>\n");
      out.write("                    <!-------------- The Modal --------------->\n");
      out.write("                    <div class=\"modal\" id=\"myModal2\">\n");
      out.write("                        <div class=\"modal-dialog\">\n");
      out.write("                            <div class=\"modal-content\">\n");
      out.write("                                <!---- Modal Header ---->\n");
      out.write("                                <div class=\"modal-header\" style=\"padding:0;margin:0;\">\n");
      out.write("                                    <img src=\"resources/img/modal_title.png\" alt=\"title\">\n");
      out.write("                                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                                </div>\n");
      out.write("                                <!---- Modal body ---->\n");
      out.write("                                <div class=\"modal-body\">\n");
      out.write("                                    <h3 style=\"color:black;\">ë¸ë¡ì ë³´ê¸°</h3>\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <a href=\"https://www.lincoln-korea.com/content/dam/lincoln/sk/nameplate/brochure/19MY-Continental.pdf\" target=\"_blank\">\n");
      out.write("                                            <img src=\"resources/img/continental.png\" alt=\"continental\"></a>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <a href=\"https://www.lincoln-korea.com/content/dam/lincoln/sk/nameplate/brochure/19MY%20MKZ%20.pdf\" target=\"_blank\">\n");
      out.write("                                            <img src=\"resources/img/mkz.png\" alt=\"mkz\"></a>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <a href=\"https://www.lincoln-korea.com/content/dam/lincoln/sk/nameplate/brochure/19MKC-Final-Brochure-2018.pdf\" target=\"_blank\">\n");
      out.write("                                            <img src=\"resources/img/mkc.png\" alt=\"mkc\"></a>    \n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <a href=\"https://www.lincoln-korea.com/content/dam/lincoln/sk/nameplate/brochure/19MY-Nautilus.pdf\" target=\"_blank\">  \n");
      out.write("                                            <img src=\"resources/img/nautilus.png\" alt=\"nautilus\"></a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!---- Modal footer ---->\n");
      out.write("                                <div class=\"modal-footer\">\n");
      out.write("                                    <img src=\"resources/img/modal_logo.png\" alt=\"logo\">\n");
      out.write("                                <!-- <button type=\"button\" class=\"btn btn-dark\" data-dismiss=\"modal\">Close</button> -->\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!--------- The Modal END --------->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("                <img src=\"resources/img/img12.png\" alt=\"ìì¹ì ì²­\" width=\"100%\" class=\"image\">\n");
      out.write("                <div class=\"caption\">\n");
      out.write("                    <h4>ìì¹ ì ì²­</h4>\n");
      out.write("                    <a href=\"#\" class=\"btn btn-outline-light text-white\" data-toggle=\"modal\" data-target=\"#myModal3\">ë°ë¡ ê°ê¸° ></a>\n");
      out.write("                    <!-------------- The Modal --------------->\n");
      out.write("                    <div class=\"modal\" id=\"myModal3\">\n");
      out.write("                            <div class=\"modal-dialog\">\n");
      out.write("                                <div class=\"modal-content\">\n");
      out.write("                                    <!---- Modal Header ---->\n");
      out.write("                                    <div class=\"modal-header\" style=\"padding:0;margin:0;\">\n");
      out.write("                                        <img src=\"resources/img/img12_2.png\" alt=\"title\">\n");
      out.write("                                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!---- Modal body ---->\n");
      out.write("                                    <div class=\"modal-body\">\n");
      out.write("                                        <h3 style=\"color:black;\">ìì¹ ì ì²­</h3>\n");
      out.write("                                        <div class=\"row\">\n");
      out.write("                                            <form action=\"booking.jsp\" method=\"post\" class=\"form-inline\" style=\"width:100%;color:black;font-size: 15px;\">\n");
      out.write("                                                <div class=\"col-sm-6\">\n");
      out.write("                                                    <label for=\"car\">ì´ë¤ ìëì°¨ì ê´ì¬ì´ ìëì? ï¼</label>\n");
      out.write("                                                    <select name=\"car\" class=\"form-control form-group\">\n");
      out.write("                                                        <option value=\"CONTINENTAL\">ë§ì»¨ CONTINENTAL</option>\n");
      out.write("                                                        <option value=\"MKZ\">ë§ì»¨ MKZ</option>\n");
      out.write("                                                        <option value=\"NAUTILUS\">ë§ì»¨ NAUTILUS</option>\n");
      out.write("                                                        <option value=\"MKC\">ë§ì»¨ MKC</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <label for=\"name\">ì´ë¦ ï¼</label>\n");
      out.write("                                                    <input type=\"text\" name=\"name\" class=\"form-control form-group\">\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <label for=\"email\">ì´ë©ì¼ ï¼</label>\n");
      out.write("                                                    <input type=\"email\" name=\"email\" class=\"form-control form-group\">\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-sm-6\">\n");
      out.write("                                                    <label for=\"plan\">ì ì°¨ë¥¼ ì¸ì  êµ¬ìí  ê³íì´ì­ëê¹? ï¼</label>\n");
      out.write("                                                    <select name=\"plan\" class=\"form-control form-group\">\n");
      out.write("                                                        <option value=\"\">ì ííì¸ì</option>\n");
      out.write("                                                        <option value=\"1m\">0-30ì¼</option>\n");
      out.write("                                                        <option value=\"3m\">1-3ê°ì</option>\n");
      out.write("                                                        <option value=\"6m\">4-6ê°ì</option>\n");
      out.write("                                                        <option value=\"a6m\">6ê°ì ì´í</option>\n");
      out.write("                                                        <option value=\"none\">ì í´ì§ ê³í ìì</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <label for=\"add\">ì¶ê°ìì²­ì¬í­</label>\n");
      out.write("                                                    <input type=\"text\" name=\"add\" class=\"form-control form-group\">\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <label for=\"place\">ì ìì¥ì ì íí´ì£¼ì¸ì. ï¼</label>\n");
      out.write("                                                    <select name=\"place\" class=\"form-control form-group\">\n");
      out.write("                                                        <option value=\"\">ì ííì¸ì</option>\n");
      out.write("                                                        <option value=\"kangseo\">ê°ì ì ìì¥(ì ì¸ìëì°¨)</option>\n");
      out.write("                                                        <option value=\"dongdaemun\">ëëë¬¸ ì ìì¥(ì ì¸ìëì°¨)</option>\n");
      out.write("                                                        <option value=\"mapo\">ë§í¬ ì ìì¥(ëíí¬ëª¨í°ì¤)</option>\n");
      out.write("                                                        <option value=\"mia\">ë¯¸ì ì ìì¥(ëíí¬ëª¨í°ì¤)</option>\n");
      out.write("                                                        <option value=\"songpa\">ì¡í ì ìì¥(íë¦¬ë¯¸ì´ëª¨í°ì¤)</option>\n");
      out.write("                                                        <option value=\"yeongdeungpo\">ìë±í¬ ì ìì¥(íë¦¬ë¯¸ì´ëª¨í°ì¤)</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                </div>\n");
      out.write("                                                <input type=\"submit\" value=\"ì ì²­íê¸°\" class=\"btn\" style=\"color:white;background:rgb(196, 95, 0);margin:auto;margin-top:15px;\">\n");
      out.write("                                            </form>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <!---- Modal footer ---->\n");
      out.write("                                    <div class=\"modal-footer\">\n");
      out.write("                                    <!-- <button type=\"button\" class=\"btn btn-dark\" data-dismiss=\"modal\">Close</button> -->\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!--------- The Modal END --------->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!------------ Third Row END -------------->\n");
      out.write("    <!---------------- Board ------------------>\n");
      out.write("    <div class=\"container\" id=\"board\">\n");
      out.write("        <h3 class=\"text-center\">ê°ì¸ì ë³´ì·¨ê¸ë°©ì¹¨</h3>\n");
      out.write("        <iframe id=\"iframe1\" src=\"http://dkfagh.dothome.co.kr/board/bbs/board.php?bo_table=board01\" width=\"100%\" onload=\"autoResize(this)\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    <!----- Board END ----->\n");
      out.write("\n");
      out.write("    <!--------------------------- DISCLOSURES --------------------------------->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <button a href=\"#disclosures\" class=\"btn btn-outline-light btn-block\" data-toggle=\"collapse\" style=\"padding:15px 0;margin-top:20px;color:#C55F07\">DISCLOSURES</a>\n");
      out.write("        <div id=\"disclosures\" class=\"collapse\" style=\"padding-bottom:10px;\">\n");
      out.write("            <p style=\"font-size: 13.4px;color:black;padding-top:20px;\">â» ë³¸ ì¬ì´í¸ì ì°¨ë ì´ë¯¸ì§, ì¬ì ë±ì ëí ì ë³´ë ê³ ê°ì ì´í´ë¥¼ ëê¸° ìí ì°¸ê³ ì© ìë£ë¡ ì¤ì  íë§¤ ëª¨ë¸ê³¼ ë¤ë¥¼ ì ììµëë¤. ì íí ì ë³´ë ê°ê¹ì´ ì ìì¥ì ììì§ììê² ë¬¸ì ë°ëëë¤.</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-------------- DISCLOSURES END ----------------->\n");
      out.write("\n");
      out.write("    <!--------------- Bottom Menu ----------------->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\" id=bottom-menu>\n");
      out.write("            <div class=\"col-sm-3\">\n");
      out.write("                <ul>\n");
      out.write("                    <h5>Vehicles</h5>\n");
      out.write("                    <li><a href=\"#\">CONTINENTAL</a></li>\n");
      out.write("                    <li><a href=\"#\">MKZ</a></li>\n");
      out.write("                    <li><a href=\"#\">AVIATOR</a></li>\n");
      out.write("                    <li><a href=\"#\">NAUTILUS</a></li>\n");
      out.write("                    <li><a href=\"#\">MKC</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-3\">\n");
      out.write("                <ul>\n");
      out.write("                    <h5>Technology</h5>\n");
      out.write("                    <li><a href=\"#\">ë§ì»¨ ì¸íë¦¬ì í¸ AWD</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-3\">\n");
      out.write("                <ul>\n");
      out.write("                    <h5>Shopping</h5>\n");
      out.write("                    <li><a href=\"#\">ì ìì¥ ë° ìë¹ì¤ì¼í° ì°¾ê¸°</a></li>\n");
      out.write("                    <li><a href=\"#\">ë¸ë¡ì ë¤ì´ë¡ë</a></li>\n");
      out.write("                    <li><a href=\"#\">MyLincoln ë§¤ê±°ì§</a></li>\n");
      out.write("                    <li><a href=\"#\">ì¸ì¼ì¦ íë¡ëª¨ì</a></li>\n");
      out.write("                    <li><a href=\"#\">ë§ì»¨ íì´ë¸ì ìë¹ì¤</a></li>\n");
      out.write("                    <li><a href=\"#\">ìì¹ ì ì²­</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-3\">\n");
      out.write("                <ul>\n");
      out.write("                    <h5>Owners</h5>\n");
      out.write("                    <li><a href=\"#\">ê³µì¸ ìë¹ì¤</a></li>\n");
      out.write("                    <li><a href=\"#\">ë¸ë ë ì´ë¸ ë©¤ë²ì­ ìë¹ì¤</a></li>\n");
      out.write("                    <li><a href=\"#\">í½ì&ëë¦¬ë²ë¦¬</a></li>\n");
      out.write("                    <li><a href=\"#\">ìëª¨ì± ë¶í ë¬´ìêµí ìë¹ì¤</a></li>\n");
      out.write("                    <li><a href=\"#\">24ìê° ê¸´ê¸ì¶ë ìë¹ì¤</a></li>\n");
      out.write("                    <li><a href=\"#\">ë³´ì¦ ë° ìë¹ì¤</a></li>\n");
      out.write("                    <li><a href=\"#\">ë¦¬ì½ ìë´</a></li>\n");
      out.write("                    <li><a href=\"#\">ì±í¬ 3 ìë°ì´í¸</a></li>\n");
      out.write("                    <li><a href=\"#\">ìì  ë¶í</a></li>\n");
      out.write("                    <li><a href=\"#\">ì°¨ë ê´ë¦¬</a></li>\n");
      out.write("                    <li><a href=\"#\">ì ë¹ ì¼ì </a></li>\n");
      out.write("                    <li><a href=\"#\">ìë¹ì¤ íë¡ëª¨ì</a></li>\n");
      out.write("                    <li><a href=\"#\">ê³ ê° ì¼í°</a></li>\n");
      out.write("                    <li><a href=\"#\">ì ìì¥ ë° ìë¹ì¤ì¼í° ì°¾ê¸°</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!---- Bottom Menu END ---->\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <button class=\"accordion\">Vehicles</button>\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            <p>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">CONTINENTAL</a></li>\n");
      out.write("                    <li><a href=\"#\">MKZ</a></li>\n");
      out.write("                    <li><a href=\"#\">AVIATOR</a></li>\n");
      out.write("                    <li><a href=\"#\">NAUTILUS</a></li>\n");
      out.write("                    <li><a href=\"#\">MKC</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("        <button class=\"accordion\">Technology</button>\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"#\">ë§ì»¨ ì¸íë¦¬ì í¸ AWD</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <button class=\"accordion\">Shopping</button>\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"#\">ì ìì¥ ë° ìë¹ì¤ì¼í° ì°¾ê¸°</a></li>\n");
      out.write("                <li><a href=\"#\">ë¸ë¡ì ë¤ì´ë¡ë</a></li>\n");
      out.write("                <li><a href=\"#\">MyLincoln ë§¤ê±°ì§</a></li>\n");
      out.write("                <li><a href=\"#\">ì¸ì¼ì¦ íë¡ëª¨ì</a></li>\n");
      out.write("                <li><a href=\"#\">ë§ì»¨ íì´ë¸ì ìë¹ì¤</a></li>\n");
      out.write("                <li><a href=\"#\">ìì¹ ì ì²­</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <button class=\"accordion\">Owners</button>\n");
      out.write("        <div class=\"panel\">\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"#\">ê³µì¸ ìë¹ì¤</a></li>\n");
      out.write("                <li><a href=\"#\">ë¸ë ë ì´ë¸ ë©¤ë²ì­ ìë¹ì¤</a></li>\n");
      out.write("                <li><a href=\"#\">í½ì&ëë¦¬ë²ë¦¬</a></li>\n");
      out.write("                <li><a href=\"#\">ìëª¨ì± ë¶í ë¬´ìêµí ìë¹ì¤</a></li>\n");
      out.write("                <li><a href=\"#\">24ìê° ê¸´ê¸ì¶ë ìë¹ì¤</a></li>\n");
      out.write("                <li><a href=\"#\">ë³´ì¦ ë° ìë¹ì¤</a></li>\n");
      out.write("                <li><a href=\"#\">ë¦¬ì½ ìë´</a></li>\n");
      out.write("                <li><a href=\"#\">ì±í¬ 3 ìë°ì´í¸</a></li>\n");
      out.write("                <li><a href=\"#\">ìì  ë¶í</a></li>\n");
      out.write("                <li><a href=\"#\">ì°¨ë ê´ë¦¬</a></li>\n");
      out.write("                <li><a href=\"#\">ì ë¹ ì¼ì </a></li>\n");
      out.write("                <li><a href=\"#\">ìë¹ì¤ íë¡ëª¨ì</a></li>\n");
      out.write("                <li><a href=\"#\">ê³ ê° ì¼í°</a></li>\n");
      out.write("                <li><a href=\"#\">ì ìì¥ ë° ìë¹ì¤ì¼í° ì°¾ê¸°</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <script>\r\n");
      out.write("        $( \".accordion\" ).accordion({\r\n");
      out.write("            collapsible: true});\r\n");
      out.write("\r\n");
      out.write("        var acc = document.getElementsByClassName(\"accordion\");\r\n");
      out.write("        var i;\r\n");
      out.write("        \r\n");
      out.write("        for (i = 0; i < acc.length; i++) {\r\n");
      out.write("        acc[i].addEventListener(\"click\", function() {\r\n");
      out.write("            this.classList.toggle(\"active\");\r\n");
      out.write("            var panel = this.nextElementSibling;\r\n");
      out.write("            if (panel.style.maxHeight) {\r\n");
      out.write("            panel.style.maxHeight = null;\r\n");
      out.write("            } else {\r\n");
      out.write("            panel.style.maxHeight = panel.scrollHeight + \"px\";\r\n");
      out.write("            } \r\n");
      out.write("        });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a href=\"https://www.facebook.com/lincolnkorea\" target=\"_blank\"><img src=\"img/facebook.png\" alt=\"facebook\" style=\"width:34px;height:34px;\"></a>\r\n");
      out.write("            <span>ë§ì»¨ ê³ ê°ì¼í° : 1600-6003  ê¸´ê¸ì¶ëìë¹ì¤ : 080-300-3673</span>\r\n");
      out.write("            <span>Copyright &copy; 2017 Ford Motor Company</span>\r\n");
      out.write("            <a href=\"https://www.lincoln-korea.com/site-map/\">Site Map</a>&nbsp;|\r\n");
      out.write("\r\n");
      out.write("            <a href=\"https://corporate.ford.com/homepage.html\">&nbsp;Global Site</a>&nbsp;|\r\n");
      out.write("\r\n");
      out.write("            <a href=\"https://www.lincoln-korea.com/privacy/\">&nbsp;Privacy</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
